function A = python_ipc_system(cmd, varargin)

  sbtag='<output_block>';
  stag='<output_item>';
  etag='</output_item>';
  ebtag='</output_block>';

  %headers = sprintf('import sympy as sp\nimport pickle\n\n');
  headers = sprintf([ 'import sys\n' ...
                      'sys.ps1 = ""; sys.ps2 = ""\n' ...
                      'import sympy as sp\n' ...
                      'from sympy import *\n' ...
                      '#import dill as pickle\n' ...
                      '\n']);

  %% load all the inputs into python as pickles
  s1 = python_copy_vars_to('ins', varargin{:});


  %% the actual command
  s2 = sprintf('%s\n\n', cmd);
  s2 = sprintf('%sout = fcn(ins)\n\n', s2);

  %% output
  s3 = python_copy_vars_from('out');

  %% use a temp file
  % todo must be a way to pass string to python -c w/o temp file
  fname = 'temp_sym_python_cmd.py';

  fd = fopen(fname, 'w');
  fprintf(fd, '# temporary autogenerated code\n\n');
  fprintf(fd, '%s\n', headers);
  fprintf(fd, '%s\n', s1);
  fprintf(fd, '%s\n', s2);
  fprintf(fd, '%s\n', s3);
  fclose(fd);

  [status,out] = system(['python ' fname]);
  if status ~= 0
    status
    out
    error('failed');
  end

  A = extractblock(out);
  % cut the "import variables success message"
  A = A(3:end);