function s = python_header()

  %s = sprintf('import sympy as sp\nimport pickle\n\n');

  s = sprintf([ ...
  'import sys\n' ...
  'sys.ps1 = ""; sys.ps2 = ""\n' ...
  'import sympy as sp\n' ...
  'from sympy import *\n' ...
  '#import dill as pickle\n' ...
  '\n' ...
  'def dbout(l):\n' ...
  '    sys.stderr.write("pydebug: " + str(l) + "\\n")\n' ...
  '\n' ...
  'def octcmd(x):\n'   ...
  '    if isinstance(x, (sp.Expr,sp.Matrix)):\n'   ...
  '        #s = "sym(\\"" + str(x) + "\\", \\"" + sp.srepr(x) + "\\")"\n'   ...
  '        #s = "sym(''" + str(x).encode("string_escape") + "'', ''" + sp.srepr(x).encode("string_escape") + "'')"\n'   ...
  '        s = "sym(''" + str(x) + "'', ''" + sp.srepr(x).replace("''", "''''") + "'')"\n'   ...
  '    #elif isinstance(x, sp.Matrix):\n'   ...
  '    #    s = "sym(''" + sp.pretty(x,use_unicode=False) + "'', ''" + sp.srepr(x) + "'')"\n'   ...
  '    elif isinstance(x, bool) and x:\n'   ...
  '        s = "true"\n'   ...
  '    elif isinstance(x, bool) and not x:\n'   ...
  '        s = "false"\n'   ...
  '    elif isinstance(x, (list,tuple)):\n'   ...
  '        s = "{"\n'   ...
  '        for y in x:\n'   ...
  '            s = s + octcmd(y) + ",  "\n'   ...
  '        s = s + "}"\n'   ...
  '    elif isinstance(x, int):\n'   ...
  '        s = str(x)\n'   ...
  '    elif isinstance(x, float):\n'   ...
  '        s = str(x)\n'   ...
  '        #FIXME\n'   ...
  '    elif isinstance(x, str):\n'   ...
  '        s = "sprintf(''" + str(x).encode("string_escape") + "'')"\n'   ...
  '        #FIXME Multiline, escape, etc\n'   ...
  '    else:\n'   ...
  '        s = "error(''python does not know how to export that'')"\n'   ...
  '    return s\n'   ...
  '\n']);
