function z = ctranspose(x)

  cmd = [ '(x,) = _ins\n'  ...
          'if x.is_Matrix:\n'  ...
          '    return ( x.H ,)\n' ...
          'else:\n' ...
          '    return ( x.conjugate() ,)' ];

  z = python_cmd (cmd, x);

