function z = times(x, y)
%.*  Array multiply.
%   Return the element-by-element multiplication product of inputs.

  cmd = [ 'def fcn(_ins):\n'  ...
          '    (x,y) = _ins\n'  ...
          '    if x.is_Matrix and y.is_Matrix:\n'  ...
          '        return ( x.multiply_elementwise(y) ,)\n' ...
          '    else:\n' ...
          '        return ( x*y ,)\n' ];
 
  z = python_sympy_cmd(cmd, sym(x), sym(y));

