function z = times(x, y)
%.*  Array multiply.
%   Return the element-by-element multiplication product of inputs.

  cmd = [ '(x,y) = _ins\n'  ...
          'if x.is_Matrix and y.is_Matrix:\n'  ...
          '    return ( x.multiply_elementwise(y) ,)\n' ...
          'else:\n' ...
          '    return ( x*y ,)' ];

  z = python_cmd (cmd, sym(x), sym(y));
