function z = transpose(x)

  cmd = [ '(x,) = _ins\n'  ...
          'if x.is_Matrix:\n'  ...
          '    return (x.T,)\n' ...
          'else:\n' ...
          '    return (x,)' ];

  z = python_cmd (cmd, x);

