function h = vertcat(varargin)

  cmd = [ 'def fcn(_ins):\n'  ...
          '    x = _ins[0]\n'  ...
          '    _proc = []\n'  ...
          '    for i in _ins:\n'  ...
          '        if i.is_Matrix:\n'  ...
          '            _proc.append(i)\n'  ...
          '        else:\n'  ...
          '            _proc.append(sp.Matrix([[i]]))\n'  ...
          '    M = sp.Matrix.vstack(*_proc)\n'  ...
          '    return (M,)\n' ];

  varargin = sym(varargin);
  h = python_sympy_cmd(cmd, varargin{:});

