function z = axplusy(a, x, y)
%AXPLUSY   helper: scalar a times sym x plus sym y
%   todo: private
%
%   todo: fail on 1x1 matrix which in sympy isn't same as scalar

  cmd = [ 'def fcn(_ins):\n'  ...
          '    (a,x,y) = _ins\n'  ...
          '    if x.is_Matrix and y.is_Matrix:\n'  ...
          '        return ( a*x+y ,)\n' ...
          '    if x.is_Matrix and not y.is_Matrix:\n'  ...
          '        return ( a*x + y*sp.ones(*x.shape) ,)\n' ...
          '    if not x.is_Matrix and y.is_Matrix:\n'  ...
          '        return ( a*x*sp.ones(*y.shape) + y ,)\n' ...
          '    else:\n' ...
          '        return ( a*x + y ,)\n' ];
 
  z = python_sympy_cmd(cmd, sym(a), sym(x), sym(y));

