function z = ctranspose(x)

  cmd = [ 'def fcn(_ins):\n'  ...
          '    (x,) = _ins\n'  ...
          '    if x.is_Matrix:\n'  ...
          '        return ( x.H ,)\n' ...
          '    else:\n' ...
          '        return ( x.conjugate() ,)\n' ];
 
  z = python_sympy_cmd(cmd, x);

