#!/usr/bin/python

# Yo dawg, I heard you like code generation so I wrote a code
# generator to write your code generators!

# TODO: make a template which we process would be nicer than this

L = 'sqrt sin cos tan asin acos atan sinh cosh tanh'

L = L.split();

for f in L:
    fname = '%s.m' % f;
    print fname

    fd = open(fname, "w")

    fd.write ("function z = %s(x)\n" % f)
    fd.write ("%");
    fd.write ("%s  Symbolic %s function\n" % (f.upper(),f))

    s = """%
%   Autogenerated, do not modify

  cmd = [ 'def fcn(ins):\\n'  ...
          '    (x,) = ins\\n'  ...
"""
    fd.write(s)
    fd.write("          '    y = sp.%s(x)\\n'  ...\n" % f)
    fd.write("          '    return (y,)\\n' ];\n")
    fd.write("\n");
    fd.write("z = python_sympy_cmd(cmd, x);\n\n");
    fd.close()


# TODO: a nice feature would be generate some units tests or something!
# perhaps call them all and then call with double and check the results are close
