function z = rdivide(x,y)
%./   elementwise forward slash division

  cmd = [ 'def fcn(_ins):\n'  ...
          '    (x,y) = _ins\n'  ...
          '    if x.is_Matrix and y.is_Matrix:\n'  ...
          '        return ( x.multiply_elementwise(y.applyfunc(lambda a: 1/a)) ,)\n' ...
          '    if not x.is_Matrix and y.is_Matrix:\n'  ...
          '        return ( y.applyfunc(lambda a: x/a) ,)\n' ...
          '    else:\n' ...
          '        return ( x/y ,)\n' ];
 
  z = python_sympy_cmd(cmd, sym(x), sym(y));

