function z = reshape(a, n, m)
%RESHAPE   Change the shape of an array

  if (nargin == 2)
    m = n(2);
    n = n(1);
  end

  cmd = [ 'def fcn(_ins):\n'  ...
          '    (A,n,m) = _ins\n'  ...
          '    if A.is_Matrix:\n'  ...
          '        #return ( A.reshape(n,m) ,)\n' ...
          '        #sympy is row-based\n' ...
          '        return ( A.T.reshape(m,n).T ,)\n' ...
          '    else:\n' ...
          '        return ( A ,)\n' ];
 
  z = python_sympy_cmd(cmd, a, n, m);

