function out = solve(eqn, vars)
%SOLVE   Symbolic solutions of eqns and systems
%   solve(x==2*x+6, x)
%   todo: out is a python list

  cmd = [ 'def fcn(_ins):\n'  ...
          '    sys.stderr.write("pydebug: " + str(_ins) + "\\n")\n'  ...
          '    d = sp.solve(*_ins)\n'  ...
          '    sys.stderr.write("pydebug: " + str(d) + "\\n")\n'  ...
          '    return (d,)\n' ];
  out = python_sympy_cmd (cmd, eqn, vars);
