function s = def_each_elem_binary(x, n)
%private

  % FIXME: Deprecated? use binop_helper

  s = { 'def _each_elem_binary(x, y, f):' ...
        '    if x.is_Matrix and y.is_Matrix:' ...
        '        z = x.copy()' ...
        '        for i in range(0, len(x)):' ...
        '            z[i] = f(x[i], y[i])' ...
        '        return z,' ...
        '    if x.is_Matrix and not y.is_Matrix:' ...
        '        return x.applyfunc(lambda a: f(a, y)),' ...
        '    if not x.is_Matrix and y.is_Matrix:' ...
        '        return n.applyfunc(lambda a: f(x, a)),' ...
        '    else:' ...
        '        return f(x, y),' };

end
