function s = def_each_elem_binary(x, n)
%private

  s = [ 'def _each_elem_binary(x,y,f):\n' ...
        '    if x.is_Matrix and y.is_Matrix:\n'                 ...
        '        z = x.copy()\n' ...
        '        for i in range(0, len(x)):\n'                  ...
        '            z[i] = f(x[i], y[i])\n'                       ...
        '        return ( z ,)\n'                               ...
        '    if x.is_Matrix and not y.is_Matrix:\n'             ...
        '        return ( x.applyfunc(lambda a: f(a,y)) ,)\n'     ...
        '    if not x.is_Matrix and y.is_Matrix:\n'             ...
        '        return ( n.applyfunc(lambda a: f(x,a)) ,)\n'     ...
        '    else:\n'                                           ...
        '        return ( f(x,y) ,)\n' ];

end
