function A = python_ipc_system(cmd, varargin)

  tag = ipc_misc_params();

  headers = python_header();


  %% load all the inputs into python as pickles
  s1 = python_copy_vars_to('_ins', varargin{:});

  %% the actual command
  % this will do something with _ins and produce _outs
  s2 = sprintf('%s\n\n', cmd);

  %% output
  s3 = python_copy_vars_from('_outs');


  %% use a temp file
  % todo must be a way to pass string to python -c w/o temp file
  fname = 'temp_sym_python_cmd.py';

  fd = fopen(fname, 'w');
  fprintf(fd, '# temporary autogenerated code\n\n');
  fprintf(fd, '%s\n', headers);
  fprintf(fd, '%s\n', s1);
  fprintf(fd, '%s\n', s2);
  fprintf(fd, '%s\n', s3);
  fclose(fd);

  [status,out] = system(['python ' fname]);
  if status ~= 0
    status
    out
    error('failed');
  end

  A = extractblock(out, tag.item, tag.enditem);
  % cut the "import variables success message"
  A = A(3:end);
