#! /bin/sh

## Generate ./configure
rm -f configure.in
echo "dnl --- DO NOT EDIT --- Automatically generated by autogen.sh" > configure.in
cat configure.base >> configure.in
files=`find . -name configure.add -print`
if test ! -z "$files" ; then
  cat $files >> configure.in
fi
cat <<EOF >> configure.in
  AC_OUTPUT(\$CONFIGURE_OUTPUTS)
  dnl XXX FIXME XXX chmod is not in autoconf's list of portable functions
  chmod 0771 octinst.sh
  echo " "
  echo "  \"\\\$prefix\" is \$prefix"
  echo "  \"\\\$exec_prefix\" is \$exec_prefix"
  AC_MSG_RESULT([\$STATUS_MSG

find . -name NOINSTALL -print    # shows which toolboxes won't be installed
])
EOF

autoconf && rm -f configure.in

## Generate ./Makeconf.in
rm -f Makeconf.in
cp Makeconf.base Makeconf.in
files=`find . -name Makeconf.add -print`
if test ! -z "$files" ; then
  cat $files >> Makeconf.in
fi

