#!/usr/bin/python
"""make_embedded_header.py

FIXME: move .py file here to src/ eventually?
"""

import sys
import os

if __name__ == "__main__":
    base = 'python_header'

    finname = '../inst/private/%s.py' % base
    foutname = '../inst/private/%s_embed.m' % base
    foutname = '../inst/private/%s_embed2.m' % base

    fd = open(finname, "r")
    l = fd.readlines()
    fd.close()

    fd = open(foutname, "w")

    fd.write("function s = %s_embed()\n" % base)
    fd.write("%")
    fd.write("%s  private\n" % base.upper())
    fd.write("%\n%")
    fd.write("  autogenerated from %s.py, edit that instead!\n\n" % base)

    fd.write("  s = '");
    for i in range(0, len(l)):
      #fd.write(l[i].encode("string_escape"))
      # bit odd, order matters, octave ok with \'' but not \'\'
      fd.write( l[i].encode("string_escape").replace("'","''").replace("%","%%") )
    fd.write("';\n");
    fd.write("\ns = sprintf(s);\n")
    fd.close()


    fd = open(foutname, "w")

    fd.write("function s = %s_embed2()\n" % base)
    fd.write("%")
    fd.write("%s  private\n" % base.upper())
    fd.write("%\n%")
    fd.write("  autogenerated from %s.py, edit that instead!\n\n" % base)

    fd.write("  s = '");
    for i in range(0, len(l)):
      #fd.write(l[i].encode("string_escape"))
      # bit odd, order matters, octave ok with \'' but not \'\'
      #fd.write( l[i].replace('\\','\\\\').encode("string_escape").replace('"','\\\\\\"').replace("%","%%") )

      # first \n to \\\n then <newline> to \n
      fd.write( l[i].replace('\\n', '\\\\\\n').replace('\n','\\n').replace('"','\\\\\\"') )
    fd.write("';\n");
    #fd.write("\ns = sprintf(s);\n")
    fd.close()

#if __name__ == "__main__":
#    embed()

